### PR TITLE
Fix web admin minor bugs

### PR DESCRIPTION
**Pull request by cinoan**
Correct 3 small issues in the web admin page.

This is my first use of git so please let me know if to would have been better to do 3 separate pull requests or if there is anything else that I should have done differently.

### CODE REVIEW

**Comment by madsci1016** [comment]
Ah, glad I checked pull requests because I was going to start resolving these too. Thanks. And your first git pull looks fine. We just have to wait for fork to approve the request.

**Comment by forkineye** [comment]
Haven't had time to work on the code much lately, thanks for doing this!

**Comment by madsci1016** [comment]
Besides the "rebooting animation placeholder" is there anything left you want to do before calling this a 2.1 release version? I've now been running your 2.1 dev code on 4 sticks and a renard adapter for a week with no issues.

**Comment by madsci1016** [comment]
Actually I just realized I never tested the "testing" mode and it needs work to by the look of it.

**Comment by cinoan** [comment]
No problem. I'm happy to look at more if it is any help, just didn't want to do more if you would rather do it yourself.

I think before a release the 'testing' options might need completing or hiding the unfinished ones just to avoid confusion.

**Comment by cinoan** [comment]
Hadn't seen the previous comment when adding that.

**Comment by madsci1016** [comment]
Yeah if no one beats me too it I'll take a whack at writing the functions for the rest of the tests in wshandler.h

**Comment by madsci1016** [comment]
A pull request for "testing" function: https://github.com/forkineye/ESPixelStick/pull/35 Wanna help 'test' it! Lol

**Comment by cinoan** [comment]
I did create a separate Rainbow test yesterday but slightly different. It was a static rainbow with selectable cycle length. I was thinking it might be useful for checking repeating elements are in the same order. From a quick look at the pull it looks like yours is better integrated in with the chase so probably better to start from that and I might try to add variable length and speed to them at some point in the future.

I've mostly been working on the view stream option and will keep going on that.

**Comment by forkineye** [comment]
Thanks both of you for working on this. I haven't had much time to work on the code lately.  One thing I wanted to point out in regards to the colorpicker and stream viewer in the test options.  It was my intention to do these using Websockets binary data.  They're currently implemented using Websockets text and aren't very efficient.  My plan is to eventually port the handlers from text to binary for network intensive stuff like those two unless you all beat me to it :)  Thanks again!

**Comment by cinoan** [comment]
I've just used binary data for a stream viewer - hopefully this is along the lines of what you were thinking off!
stream

The code currently assumes it will be the only binary data to the client as I didn't expect there to be anything else of any size - It might not be that efficient to send the colorpicker as text but it isn't going to get set that often.

**Pull request merged**
