### PR TITLE
Reduced RAM usage to make the UI more stable.

### PR DESCRIPTION
**Pull request by MartinMueller2003**
Significant rework to remove all uses of the Web Socket facilities. This resulted in a heap increase on the ESP8266 by 12KB which makes the UI much more stable. Made changes to try and have only a single HTTP request out to the ESP at a time. Can't do that for the initial load, but the extra heap makes it possible to get beyond initial page load.

### CODE REVIEW

**Comment by dkulp** [comment]
One important note:  this will completely break xLights integration.   xLights currently uses the websocket API's for configuring everything.

**Comment by MartinMueller2003** [comment]
@dkulp 
Did a clean xLights build (no changes yet) And I get some errors. Any hints?

image

**Comment by dkulp** [comment]
I believe you forgot the  --recurse-submodules  when you did the git clone.   A "git submodule update --init" should get all the submodules updated.

**Comment by MartinMueller2003** [comment]
that did it. thank you

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 13, 2023 at 19:11, Daniel ***@***.***> wrote:   


I believe you forgot the --recurse-submodules when you did the git clone. A "git submodule update --init" should get all the submodules updated.

**Comment by forkineye** [comment]
I'm going to go ahead and merge this so we can all stay in sync as I'm working on some things as well.  Martin said he's working on the xLights configuration part so it won't be broke for very long.  We'll drop a new release after more testing.

**Pull request merged**
