### PR TITLE
Add Websocket Queue

### LINKED ISSUE #65: Need to verify if websocket data is revceived
Sometimes, configuration data fails to show up in the web UI.  Root cause is unknown, however configuration receipt verification / re-querying should be done to prevent this from happening.
Example: https://diychristmas.org/vb1/showthread.php?7969-ESPixelStick-WiFi-Renard-amp-Pixel-Control-from-XLights&p=88776&viewfull=1#post88776

### PR DESCRIPTION
**Pull request by cinoan**
Queue websocket requests from the client to avoid an issue with the server not receiving/responding to all requests if sent together.  Fixes #65

### CODE REVIEW

**Comment by forkineye** [comment]
Thank you! This was the only thing holding up 3.0 and I've just been so busy lately that I haven't had time to work on the code.  I'm out of town, but will merge and test next week. Thanks again!

**Comment by cinoan** [comment]
Definitely needs a good test but seems ok here and the interface works well on my Galaxy S8 now which always hit the issue before.

**Comment by penfold42** [comment]
It seems to be really laggy on the static test.

In the past you could set the colour in real time but now it’s laggy. Even a single click on a colour might take a second to show up on the leds

**Comment by cinoan** [comment]
Yes I saw the issue yesterday and wondered if it was in this version or was remnants from another commit I reverted, The issue is that when a request is sent it waits for a reply before sending the next message, or times out after 2 seconds. As the test mode requests don't get a response the get caught in this delay.  I'll work on a fix now.

**Pull request merged**
