### PR TITLE
add mDNS service

### PR DESCRIPTION
**Pull request by jnovack**
Add mDNS service advertising both **fpp** and **http** services.

```none
❯ dns-sd -B _fpp._udp .
Browsing for _fpp._udp
DATE: ---Thu 31 Dec 2020---
18:30:04.812  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
18:30:04.812  Add        3   4 local.               _fpp._udp.           esps-2ee280

❯ dns-sd -B _http._tcp .
Browsing for _http._tcp
DATE: ---Thu 31 Dec 2020---
18:30:16.458  ...STARTING...
Timestamp     A/R    Flags  if Domain               Service Type         Instance Name
18:30:16.459  Add        3   4 local.               _http._tcp.          esps-2ee280

❯ dns-sd -G v4 esps-2ee280
DATE: ---Thu 31 Dec 2020---
18:32:36.710  ...STARTING...
Timestamp     A/R    Flags if Hostname              Address             TTL
18:32:36.713  Add        2  0 esps-2ee280.local.    10.10.10.200        4502
```

Console Output
```
ESPixelStick v4.0-dev (NOT STABLE)(Dec 31 2020 - 18:17:11)
ESP Version: SDK:2.2.2-dev(38a443e)/Core:2.7.3-3-g2843a5ac=20703003/lwIP:STABLE-2_1_2_RELEASE/glue:1.2-30-g92add50/BearSSL:5c771be
Flash File system initialized.
Listing directory: /
'config.json': 	'294'
'input_config.json': 	'1297'
'output_config.json': 	'1266'
No SD card installed
Configuration file: '/config.json' loaded.
** OutputDisabled Initialization for Chan: 0 **
** OutputDisabled Initialization for Chan: 1 **
Configuration file: '/output_config.json' loaded.

WiFi Entering State: Connecting Using Config Credentials

WiFi Connecting to YOUR_MOM as esps-2ee280
** 'Disabled' Initialization for input: '0' **
** 'Disabled' Initialization for input: '1' **
Configuration file: '/input_config.json' loaded.
- Web Server started on port 80
FPPDiscovery subscribed to broadcast
FPPDiscovery subscribed to multicast: 239.70.80.80
WiFi Reset has been requested
Error setting up MDNS responder!
Error setting up MDNS responder!
Error setting up MDNS responder!
mDNS responder started.

WiFi Entering State: Connecting Using Config Credentials

WiFi Connecting to YOUR_MOM as esps-2ee280
.
WiFi Entering State: Connected To AP
WiFI: ERROR: STATIC SELECTED WITHOUT IP. Using DHCP assigned address
WiFi Connected with IP: 10.10.10.200
```

### CODE REVIEW

**Comment by MartinMueller2003** [comment]
This build did not have the littlefs uploaded.

**Comment by jnovack** [comment]
I'm sorry, I don't understand the significance of your statement.  Would you kindly add context and at least one action for me to perform (preferably with detail) as to how I may satisfy any additional constraints?

**Comment by MartinMueller2003** [comment]
Sorry. I went through your logs again. It is the SD file system that did not get loaded and that is most likely because you do not have an SD card attached to the ESP.

**Comment by MartinMueller2003** [comment]
I am a GIT Newbe so I cant figure out how to embed comments in the comparisons. So my comments are here.

mDNS.Begin(...) should not only be called in the WiFi Reset operation. There is currently a bug that causes the WiFi to get reset on boot. Once that gets fixed, your startup function would not get called.

In mDNS.cpp:

- you are including a bunch of WiFi files but never using any of the objects they define. Can you remove the extra includes? Also, you included the InputMgr definitions. I am pretty sure you dont need them.
- Your begin function is an endless loop with a sleep in it. This is not allowed. It can cause other parts of the system to get messed up. What problem is this loop fixing? Should you maybe use a state machine or hook into the WiFi events to update the mDNS records when the WiFi interface comes up?
- Infinite loops are never a good thing. The ESP can be hung and happy. Frustrating to the user.
- Does mDNS.update really need to be called every millisecond or even multiple times per millisecond? Can this be made less intensive with a timer tick handler (again, part of a state machine?)

in mDNS.h
- The mDNS.h file brings in the same WiFI includes the CPP file brings in. Do those files really need to be there for all users of the mDNS interface?
- You did not include a destructor. 

General comments: 

- You have not provided a mechanism to turn on/off mDNS support. We may not want to advertise a specific device using mDNS. 
- Hard Coded advertisements: You should not assume FPP is to be advertised. You should provide an API by which a service can de/register itself when the service changes state..

**Comment by jnovack** [comment]
No problem, thanks for the feedback.  You can click on "Files Changed" and then click on the blue plus sign that pops up between the line number and my added line, this starts a review.  Then you may comment on each section.  Finally, when the review is done, in the upper right, you can click "Request Changes" which marks this as requiring changes.

**Comment by forkineye** [comment]
Closing this one out. May consider mDNS as optional in the future.

**Pull request closed without merging**
