### PR TITLE
Added ArtNet, OLED Display, Factory Reset and Multi Universe

### PR DESCRIPTION
**Pull request by Jearde**
I hope some of the features will help someone.
I think the OLED Driver is not necessary, but useful.
The structure of the protocol config could be helpful for adding MQTT implementation, if lib is in the same structure.
Connecting the Default-Pin to Ground will erase EEPROM config on startup.

### CODE REVIEW

**Comment by forkineye** [comment]
I'm not dead set on adding ArtNet yet, as I thought it was on its way out.  Are there some specific sources you're using that can't use e1.31 or a particular reason to use ArtNet?  I'm in the middle of revamping the web / configuration frontend and the current design doesn't flow well with multiple input options. That said, I am planning on adding MQTT support as I believe I can have it live along with e1.31 for static override control.

**Comment by madsci1016** [comment]
I'd also vote no on Artnet, as it would only be used by a very small percentage of the user base and contribute to the code space required by everyone. I'd suggest maintaining a fork with Artnet support for special use cases.

**Comment by Jearde** [comment]
I agree to you. E1.31 is the better standart, but I thought, that someone would be happy about it. I am a event technician and every program is able to understand ArtNet, but sACN isn't so common. E.g. Resolume Arena only supports ArtNet. The OLED is useful for me, too. So I am able to identify the modules very easily, which is important for my job.
I think, that it is not necessary to merge the code, but if someone could be happy about the pull request, he can use it.
And if someone noticed some issues, I would be happy, to know them.

**Comment by forkineye** [comment]
Basic MQTT support is in and Art-Net support is planned for 3.1. Multi universe been in for a while and configuration is handled differently now and doesn't use eeprom.  OLED would be nifty but out of scope for the target hardware. If you want to maintain OLED in your own fork, recommend be starting with a fresh pull be as many things have been improved.

**Pull request closed without merging**
