### PR TITLE
Added ZigZag Support

### PR DESCRIPTION
**Pull request by gizmohd**
I used something very similar to this for the Komby Boards... thought you could use it in the ESPixelStick as well...

### CODE REVIEW

**Comment by forkineye** [comment]
You think anyone would ever need this for serial? I was thinking of making it pixel only and putting it in the pixeldriver code.

**Comment by madsci1016** [comment]
It likely will mostly be used for Pixel; if it's quicker to add it there than I think that's ok. But if it's the same amount of work why not make it output independent? 

Actually scratch that, when you consider the need to figure out the zig zag by pixel element vs. channel (IE, you zig zag the sets of three channels, not the channels so you don't mess up RGB channel mapping) it's easier to just consider it always a pixel.

**Comment by gizmohd** [comment]
Have to agree with Bill... more than likely just a pixel thing....

**Comment by penfold42** [comment]
Done for ws2811 in #147

**Pull request closed without merging**
