### PR TITLE
Pwm support with web config

### PR DESCRIPTION
**Pull request by penfold42**
Features:
Web config under device section
Map any Dmx channel to a PWM gpio output
Coexists with both serial and pixel mode
Selectively enable each gpio pin with optional inverted logic.
Conditional compile flag if you don't want to include this.

### CODE REVIEW

**Comment by forkineye** [comment]
I'm closing to releasing 3.0 final then will merge this in.  Should wrap it up this weekend, thanks!

**Comment by tpmodding** [comment]
works for me...when will it merged?

**Comment by forkineye** [comment]
I plan on merging it once https://github.com/forkineye/ESPixelStick/issues/65 is fixed. That's the only thing holding up 3.0, I just haven't had time to work on the code lately.

**Comment by forkineye** [comment]
@cinoan just submitted a fix for #65 which was holding this up.  I'll be testing 3.0 next week and merge this once 3.0 is tagged and conflicts are resolved. Thanks!

**Comment by penfold42** [comment]
Cool !

Thankfully the conflicts look trivial.

**Pull request closed without merging**
