### PR TITLE
Update to first fully functional version. Time to start Alpha testing.

### PR DESCRIPTION
**Pull request by MartinMueller2003**

### CODE REVIEW

**Comment by forkineye** [comment]
Was this supposed to be the Unify branch? All this stuff is dated. I see #215 as well.

**Comment by MartinMueller2003** [comment]
hI Shelby
yes this is for the unify branch. i have gotten it all working plus a lot of features that others have asked for. fyi: i am in the process of adding rgbw support to the pixel driver.
martin

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 12, 2020 at 18:32, Shelby Merrick<notifications@github.com> wrote:   


Was this supposed to be the Unify branch? All this stuff is dated. I see #215 as well.

**Comment by MartinMueller2003** [comment]
Been thinking back, I did have a pull request on the master branch that I made a long time ago. You can abandon that one. The more recent pull requests on the Unify branch are much better implementations and have all the cool new features.
Martin
    On Monday, October 12, 2020, 07:27:48 PM EDT, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
 hI Shelby
yes this is for the unify branch. i have gotten it all working plus a lot of features that others have asked for. fyi: i am in the process of adding rgbw support to the pixel driver.
martin

Sent from Yahoo Mail on Android 
 
  On Mon, Oct 12, 2020 at 18:32, Shelby Merrick<notifications@github.com> wrote:   


Was this supposed to be the Unify branch? All this stuff is dated. I see #215 as well.

**Comment by forkineye** [comment]
Weird, it's showing against the master branch with your last commit back in April. Do you want to merge #215 instead (it's showing august) or you want to create a new one against the unify branch?

**Comment by MartinMueller2003** [comment]
It looks like 215 is the correct one. Yes the changes start in august and go all the way up to Oct 12.



    On Tuesday, October 13, 2020, 04:33:42 PM EDT, Shelby Merrick <notifications@github.com> wrote:  
 
 


Weird, it's showing against the master branch with your last commit back in April. Do you want to merge #215 instead (it's showing august) or you want to create a new one against the unify branch?

**Comment by MartinMueller2003** [comment]
Hi Shelby
I would love to have a conversation with you. I have no idea whether I am taking this in a direction you approve of and I am stuck with the device config UI. It works, but it does not have the "splash?" a cool device like this should have.
Martin
    On Tuesday, October 13, 2020, 06:17:48 PM EDT, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
  It looks like 215 is the correct one. Yes the changes start in august and go all the way up to Oct 12.



    On Tuesday, October 13, 2020, 04:33:42 PM EDT, Shelby Merrick <notifications@github.com> wrote:  
 
 


Weird, it's showing against the master branch with your last commit back in April. Do you want to merge #215 instead (it's showing august) or you want to create a new one against the unify branch?

**Comment by forkineye** [comment]
>It looks like 215 is the correct one. Yes the changes start in august and go all the way up to Oct 12.
Ok, I'll close this one out and merge in 215.  I should be able to pull whatever is newer from your unify branch.

> Hi Shelby I would love to have a conversation with you. I have no idea whether I am taking this in a direction you approve of and I am stuck with the device config UI. It works, but it does not have the "splash?" a cool device like this should have.
I appreciate all the hard work you and @dkulp have been putting into this.  I had actually started working on cleaning up the config UI pages with your last PR, but run out of time to work on it.  I'll get everything in sync this week and get some ideas down on the UI flow.  There's a couple of more things I'm wanting to add, but I'm loving it so far. Thanks again!

**Comment by MartinMueller2003** [comment]
@dkulp 
Would you please take a look at the changes in this diff:

https://github.com/smeighan/xLights/compare/master...MartinMueller2003:xLights:master

I have been getting the ESP upload / download updated and I think it is ready for a pull request.

**Pull request closed without merging**
