### PR TITLE
Add user settable Gamma

### PR DESCRIPTION
**Pull request by penfold42**
- the existing LUT is re-computed on changes.
- Added "Gamma Value" to webUI to configure.
- It defaults to 2.2 if missing or <= 0
- It is served up on http://a.b.c.d/gamma for verification
- svg graph at http://a.b.c.d/gamma.html
- Value stored in config.json:
```
"pixel":{"type":0,"color":0,"gamma":true,"gammaVal":1.5}
```

### CODE REVIEW

**Comment by cinoan** [comment]
I haven't had chance to look at code for a while but I was just wondering if rolling in a maximum brightness setting into this gamma calculation would be a good idea. Having it integrated into the gamma curve would save any extra calculation during the output, or any changes to the output, and would be more accurate than a rounded gamma curve that you then reduce by x% (though I doubt anyone would see the difference!). It should be minor changes now all this has been done. 

The one issue I can think of is gamma correction would have to be on for maximum brightness to have an effect but, since the extra overhead of gamma correction doesn't seem to make a difference, maybe it could be changed to be always on anyway. Then it is just whether you make the default gamma 1 or 2.2.

Just an idea.

**Comment by penfold42** [comment]
I like having a boolean on/off in the GUI, but the implementation under the hood could just as easily use 1.0 as the gamma if it is "off".

How do you see maximum brightness implemented mathematically?
is it simply a hard cap? 
`if (bright > max_bright) bright = max_bright;`
Or a scaling?
`bright = bright*max_bright/255`

**Comment by cinoan** [comment]
I was thinking that it could be including in the gamma calculation so 
`GAMMA_2811[i] = (uint8_t) 255.0 * pow(i/255.0, gammaVal) + 0.5;`
becomes
`GAMMA_2811[i] = (uint8_t) max_bright * pow(i/255.0, gammaVal) + 0.5;`
Effectively just a scaling, though doing it with the gamma calculation avoids values getting rounded twice and so being slightly less accurate.

**Comment by penfold42** [comment]
Got it - I’ll add a brightness factor to the GUI where 1.0 is normal and support over driving the leds

Gut feel says it should be done inside the pow() so applies before the gamma curve

**Comment by penfold42** [comment]
@forkineye - your thoughts ?
Btw, I included these gamma commits in the pwm pull request - should I just close this PR ?

**Comment by forkineye** [comment]
I've had a few requests for brightness as well so it'd be nice to have both.  @penfold42 You can include it in the other PR if you want.  I'll merge it once the websocket stuff is wrapped up and 3.0 is tagged.

**Comment by penfold42** [comment]
Will implement brightness and we can merge it all with pwm #66

Closing this PR

**Comment by penfold42** [comment]
brightness has now been implemented in the pwm branch.
https://github.com/forkineye/ESPixelStick/pull/66/commits/5ab8a2fd0d85d007a6d87ca2ba6b4bbe96db36ae

**Pull request closed without merging**
