### PR TITLE
Fixed "null" in ssid. 

### PR DESCRIPTION
**Pull request by MartinMueller2003**
Added hidden as default for input status blocks

### CODE REVIEW

**Comment by patdelaney** [comment]
Just pulled in Unify from Shelby and build manually. Now SSID and PD show blank.
image

**Comment by MartinMueller2003** [comment]
Did you set one? 
We used to overwrite the users setting with the default setting when we connected using the default credentials. That caused a problem for me. I was setting up an ESP at home and configuring the ESP to connect at a remote location. Having the config get overwritten every time the device connected to my home network seemed wrong to me. The status page tells you which SSID was used. 
So now the configuration page tells you what has really been configured. If you did not configure anything then it will be empty.
Opinions?
Martin
    On Wednesday, January 13, 2021, 08:18:46 AM EST, patdelaney <notifications@github.com> wrote:  
 
 


Just pulled in Unify from Shelby and build manually. Now SSID and PD show blank.

**Comment by patdelaney** [comment]
OK I think I understand what you said, but I think it's a change is what the software 3.x currently does, and it doesn't seem user intuitive.  Plus the empty fields are showing the green check mark (valid) in the blank SSID and Password fields.

**Comment by MartinMueller2003** [comment]
OK. What I can do is on new config create I can put in the default credentials, but not at connect time (like it used to be). That way there will be a starting value and the user can overwrite it as needed.
Martin
    On Wednesday, January 13, 2021, 08:33:42 AM EST, patdelaney <notifications@github.com> wrote:  
 
 


OK I think I understand what you said, but I think it's a change is what the software 3.x currently does, and it doesn't seem user intuitive. Plus the empty fields are showing the green check mark (valid) in the blank SSID and Password fields.

**Comment by MartinMueller2003** [comment]
Fix has been pushed to my branch
Martin
    On Wednesday, January 13, 2021, 08:38:57 AM EST, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
  OK. What I can do is on new config create I can put in the default credentials, but not at connect time (like it used to be). That way there will be a starting value and the user can overwrite it as needed.
Martin
    On Wednesday, January 13, 2021, 08:33:42 AM EST, patdelaney <notifications@github.com> wrote:  
 
 


OK I think I understand what you said, but I think it's a change is what the software 3.x currently does, and it doesn't seem user intuitive. Plus the empty fields are showing the green check mark (valid) in the blank SSID and Password fields.

**Pull request merged**
