### PR TITLE
Fix Start Chanel >1, Add view stream test 

### PR DESCRIPTION
**Pull request by cinoan**
main loop e131 to setValue code wasn't handling start channels > 1  correctly causing problems if the channel count spanned universes.

Added a view of current output onto the testing page for the view stream option (hopefully that was what you were expecting!). Initially started to send each universe separately (which was how the above bug was found) but found the ESPAsyncWebServer would cause exceptions under heavy work. Then realised the much easier way of sending the pixdata/_serialdata. Update speed is controlled by how fast the client can draw the screen

### CODE REVIEW

**Comment by madsci1016** [comment]
Eh, only issue is since we aren't coordinating this effort, both our pull requests are in conflict now.

**Comment by madsci1016** [comment]
@forkineye Do you have time to pull in both requests and solve the conflicts? If not I'll make an attempt to do so.

**Comment by cinoan** [comment]
My changes are smaller so I'm happy to resubmit them based on the code after your pull has been merged.

**Comment by madsci1016** [comment]
I'm not super experienced with git either, but there's way to pull request from any branch/fork to another. You could pull from my fork into yours, make the changes and then submit a pull from yours to the main base. Then yours would supersede mine but have everything. Not sure if that's the 'right way though'.

I'm debating pulling from your request into mine and trying to resolve the conflict myself, but wanted to get @forkineye input since he's the expert.

**Comment by forkineye** [comment]
Sorry @cinoan and @madsci1016, haven't had a chance to check the merges yet.  I'll try to get to it tomorrow and resolve the conflicts.

**Comment by cinoan** [comment]
I have pulled @madsci1016 changes into a branch (https://github.com/cinoan/ESPixelStick/tree/mergetest) and have fixed the conflicts (they were all quite clear). I'm just testing the complete code and have a couple of things I will quickly fix before submitting it. (Sorry about the extra mege commits)

**Comment by madsci1016** [comment]
So view stream test in serial mode is giving odd results. How did you plan to handle it in that mode? All boxes white and just fade to channel value?

**Comment by madsci1016** [comment]
Nevermind, fixed in https://github.com/forkineye/ESPixelStick/pull/38

**Pull request merged**
