### PR TITLE
Added SoftAP

### PR DESCRIPTION
**Pull request by madsci1016**
It was easy. Tested and verified will fail to softAP upon bad configuration.

### CODE REVIEW

**Comment by forkineye** [comment]
That's too easy, lol!  I'll pull it and check it out this week when I get time, thanks!!

**Comment by madsci1016** [comment]
Yep, hardest part was trying to get Git to rebase my fork so I could start working on your latest version. Next is to start adding Renard support to this new version which would require adding another framework layer to do 'right'. IE, since you have pulled GECE and WS2811 into a 'pixel driver' that standardizes the interaction with the main sketch It might make sense to have a 'serial driver' that would have support for Renard and DMX for example. Then the main loop would have to have a routine for either pixel output or serial output.

**Comment by madsci1016** [comment]
Well, threw together the serial drivers. No changes on main sketch yet so it should be a safe pull.

**Comment by forkineye** [comment]
When I roll your serial stuff in, I'm thinking of a "Mode" config from the Admin page.  For now, it would be "Pixel" and "Serial", presenting different root page layouts to keep the interface clean and somewhat dedicated to the task.  I have a handful of other modes in mind as well and this will open up room for expansion while keeping it clean.

**Comment by madsci1016** [comment]
Done. Admin page now has 'MODE' selection. Changes root to show 'Pixel Config' or 'Serial config'. Tested against a strip of WS2811 strips and a Renard SS 24. Need to test DMX output next.

**Comment by madsci1016** [comment]
Image of Admin

**Comment by forkineye** [comment]
@madsci1016 Thanks for doing this!  I plan on merging this all in once I get this current GB done and shipped.

**Comment by madsci1016** [comment]
No problem. 

I'm a little worried if a 10 second timeout is too short before switching to AP mode. But thus far with 7 already 'in the field' I haven't seen a problem yet.

**Comment by asavartsov** [comment]
I actually didn't like the way it proposed to work. I think that controller shouldn't silently fall back to this mode and shoud try to connect to preconfigured network. It might be better to add check for empty SSID in config and switching to SoftAP mode if no SSID is configured. For cases when the preconfigured network SSID isn't available anymode or password was changed, config reset button could be added on some unused GPIO pin to erase EEPROM when pressed at ESP power on.

**Comment by madsci1016** [comment]
There's already several hardware versions 'in the field' that don't have a config reset button, so i don't believe making the default require one for reset is a smart idea when we (or maybe just I) believe this should be kept as one firmware image for all types of ESP drivers. 

Instead, I suggest a 3-5 minute 'retry' timer so it will only stay in softAP for that time before rebooting and trying to connect to the configured AP again. 

I used 12 of these in my yard last year with the softAP fallback and had little issue. The few times it did fall back in softAP I would have been fine if it was only for 5 mins, as suggested.

**Comment by madsci1016** [comment]
@forkineye do you have time to merge the request? I'd love to keep this ESP stuff as one repository to avoid further splintering. @GraysonLough fixed up the DMX code on my fork so this is becoming a one stop shop for ESP control

**Comment by GraysonLough** [comment]
I'd like to see these merged as well, I feel that this is becoming an all in one solution for using the ESP to control any of the lighting stuff out there.  Especially given the versatility of the pixel stick, the renardESP, and then what I am getting ready to release which would be a 5V powered ESPDmxStick to allow integration into the LOR Controllers, or anything else really out there on the market.  I've personally got 20 pixel sticks, 6 renardESP's, and will soon have a few other generic DMX sticks to introduce to the yard this year.

**Comment by Jearde** [comment]
Me, too, but I merged it by myself and programmed a library for ArtNet support, which is based on the sACN library and added a OLED display library for showing some configs and the ip. I will push my code, when I fixed some issues and tested it, but it seems to work.

**Comment by forkineye** [comment]
Just got back from vacation, I'll get these merged in this week.

**Pull request merged**
