### PR TITLE
Unify

### PR DESCRIPTION
**Pull request by MartinMueller2003**
Major changes to stabilize ESP32
Added FPP FSEQ player support
Removed ZCPP

### CODE REVIEW

**Comment by forkineye** [comment]
Ended up losing all the commit history when I merged it cause there were some conflicts I needed to resolve. Going to revert it and try again.

**Comment by forkineye** [comment]
Should be fixed now

**Comment by MartinMueller2003** [comment]
Thanks Shelby
    On Wednesday, October 14, 2020, 12:53:25 PM EDT, Shelby Merrick <notifications@github.com> wrote:  
 
 


Should be fixed now

**Comment by MartinMueller2003** [comment]
Hi Shelby
I am working on the firmware upload utility. Added the ability to select one of multiple HW platform definitions. The problem I am encountering is with the reset mechanism used by my LoLin ESP32 platform. The version of the esptool used by the Arduino IDE has no problems uploading code and data to the ESP. The version you have included with the firmware tool does not seem to be able to get the ESP32 into the upload mode. 
   
   - Is there a reason you chose the version currently included as opposed to one of the python versions?
   - Is there a newer version of the tool available? 
   - Which tool did you incorporate into the tool?

Martin 
    On Wednesday, October 14, 2020, 01:07:54 PM EDT, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
  Thanks Shelby
    On Wednesday, October 14, 2020, 12:53:25 PM EDT, Shelby Merrick <notifications@github.com> wrote:  
 
 


Should be fixed now

**Comment by forkineye** [comment]
> Hi Shelby I am working on the firmware upload utility. Added the ability to select one of multiple HW platform definitions. The problem I am encountering is with the reset mechanism used by my LoLin ESP32 platform. The version of the esptool used by the Arduino IDE has no problems uploading code and data to the ESP. The version you have included with the firmware tool does not seem to be able to get the ESP32 into the upload mode.  - Is there a reason you chose the version currently included as opposed to one of the python versions? - Is there a newer version of the tool available?  - Which tool did you incorporate into the tool?

I'm using original native compiled versions of the tool. I didn't move to the python version as I didn't want to have to bring along more dependencies. However, I'm having users experiencing issues flashing on the latest MacOS releases now so I need to look into changing it. I just don't want to require users to install python in order to flash.

**Comment by MartinMueller2003** [comment]
I brought in the latest compiled version but it is still five years old and did not really behave very well. It did get past the connection stage but still failed to upload the file. I have been working with the python version to see what the magic incantation needs to be to get it to work. The Arduino IDE seems to have no issue so I am sure the problem is in the parameters sent to the tool. Trying to work through it. I will not get much done over the weekend. Will get back to it on Monday.
FYI: I added a selection for the device attributes. Do you want me to push what I have?
Martin
    On Friday, October 23, 2020, 02:15:36 PM EDT, Shelby Merrick <notifications@github.com> wrote:  
 
 



Hi Shelby I am working on the firmware upload utility. Added the ability to select one of multiple HW platform definitions. The problem I am encountering is with the reset mechanism used by my LoLin ESP32 platform. The version of the esptool used by the Arduino IDE has no problems uploading code and data to the ESP. The version you have included with the firmware tool does not seem to be able to get the ESP32 into the upload mode.  - Is there a reason you chose the version currently included as opposed to one of the python versions? - Is there a newer version of the tool available?  - Which tool did you incorporate into the tool?


I'm using original native compiled versions of the tool. I didn't move to the python version as I didn't want to have to bring along more dependencies. However, I'm having users experiencing issues flashing on the latest MacOS releases now so I need to look into changing it. I just don't want to require users to install python in order to flash.

**Comment by MartinMueller2003** [comment]
Good Day Shelby
I just created a pull request for my latest batch of changes. I have been getting feedback from an Alpha tester that has been incorporated into the UI. Also tracked down some crashes caused by low memory when the UI is active.
I think there is a bug in the frame time calculation when using the White channel. Will track that down shortly. I think I will make the inter frame gap configurable so that we can support a wider range of pixels without having to touch the code. 
Martin
    On Friday, October 23, 2020, 06:04:06 PM EDT, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
  I brought in the latest compiled version but it is still five years old and did not really behave very well. It did get past the connection stage but still failed to upload the file. I have been working with the python version to see what the magic incantation needs to be to get it to work. The Arduino IDE seems to have no issue so I am sure the problem is in the parameters sent to the tool. Trying to work through it. I will not get much done over the weekend. Will get back to it on Monday.
FYI: I added a selection for the device attributes. Do you want me to push what I have?
Martin
    On Friday, October 23, 2020, 02:15:36 PM EDT, Shelby Merrick <notifications@github.com> wrote:  
 
 



Hi Shelby I am working on the firmware upload utility. Added the ability to select one of multiple HW platform definitions. The problem I am encountering is with the reset mechanism used by my LoLin ESP32 platform. The version of the esptool used by the Arduino IDE has no problems uploading code and data to the ESP. The version you have included with the firmware tool does not seem to be able to get the ESP32 into the upload mode.  - Is there a reason you chose the version currently included as opposed to one of the python versions? - Is there a newer version of the tool available?  - Which tool did you incorporate into the tool?


I'm using original native compiled versions of the tool. I didn't move to the python version as I didn't want to have to bring along more dependencies. However, I'm having users experiencing issues flashing on the latest MacOS releases now so I need to look into changing it. I just don't want to require users to install python in order to flash.

**Comment by MartinMueller2003** [comment]
Hi Shelby
esptool is turning into a serious PITA. I found a precompiled set of mkspiffs for the ESP8266 and ESP32 (yes they are different). Got them for all of the build platforms. The latest pre compiled version I found for esptool that is compiled for all four platforms is from 2018 and does not work with my newer ESP32 board. A newer precompiled esptool (that does not have OSX or linux versions) does work with my newest ESP32 board. The latest python version also works with my newer ESP32 board. 

Do you know how to pre compile python into target platform executables?
Martin

    On Monday, October 26, 2020, 07:39:10 AM EDT, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
  Good Day Shelby
I just created a pull request for my latest batch of changes. I have been getting feedback from an Alpha tester that has been incorporated into the UI. Also tracked down some crashes caused by low memory when the UI is active.
I think there is a bug in the frame time calculation when using the White channel. Will track that down shortly. I think I will make the inter frame gap configurable so that we can support a wider range of pixels without having to touch the code. 
Martin
    On Friday, October 23, 2020, 06:04:06 PM EDT, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
  I brought in the latest compiled version but it is still five years old and did not really behave very well. It did get past the connection stage but still failed to upload the file. I have been working with the python version to see what the magic incantation needs to be to get it to work. The Arduino IDE seems to have no issue so I am sure the problem is in the parameters sent to the tool. Trying to work through it. I will not get much done over the weekend. Will get back to it on Monday.
FYI: I added a selection for the device attributes. Do you want me to push what I have?
Martin
    On Friday, October 23, 2020, 02:15:36 PM EDT, Shelby Merrick <notifications@github.com> wrote:  
 
 



Hi Shelby I am working on the firmware upload utility. Added the ability to select one of multiple HW platform definitions. The problem I am encountering is with the reset mechanism used by my LoLin ESP32 platform. The version of the esptool used by the Arduino IDE has no problems uploading code and data to the ESP. The version you have included with the firmware tool does not seem to be able to get the ESP32 into the upload mode.  - Is there a reason you chose the version currently included as opposed to one of the python versions? - Is there a newer version of the tool available?  - Which tool did you incorporate into the tool?


I'm using original native compiled versions of the tool. I didn't move to the python version as I didn't want to have to bring along more dependencies. However, I'm having users experiencing issues flashing on the latest MacOS releases now so I need to look into changing it. I just don't want to require users to install python in order to flash.

**Comment by forkineye** [comment]
I know there's py2exe for Window, and that may be the only platform we need to compile for. I'd say 99% of the Linux users would already have Python installed from their distro. I need to look at MacOS and see if it's there by default as well.

**Comment by MartinMueller2003** [comment]
Hi Shelby
It would be great if we could go with python on the linux/unix platforms. I will grab the latest python version and see if I can get it to work and then convert it to an exe. I also have a bunch of minor fixes that I will submit today.
Martin

    On Thursday, October 29, 2020, 08:36:06 AM EDT, Shelby Merrick <notifications@github.com> wrote:  
 
 


I know there's py2exe for Window, and that may be the only platform we need to compile for. I'd say 99% of the Linux users would already have Python installed from their distro. I need to look at MacOS and see if it's there by default as well.

**Comment by MartinMueller2003** [comment]
pull request for flashtool has been created. This uses esptool.py for non windows and a python shell program for windows execution. Not sure this will be the final configuration but it is working on my latest ESP32
Martin
    On Thursday, October 29, 2020, 09:34:05 AM EDT, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
  Hi Shelby
It would be great if we could go with python on the linux/unix platforms. I will grab the latest python version and see if I can get it to work and then convert it to an exe. I also have a bunch of minor fixes that I will submit today.
Martin

    On Thursday, October 29, 2020, 08:36:06 AM EDT, Shelby Merrick <notifications@github.com> wrote:  
 
 


I know there's py2exe for Window, and that may be the only platform we need to compile for. I'd say 99% of the Linux users would already have Python installed from their distro. I need to look at MacOS and see if it's there by default as well.

**Comment by MartinMueller2003** [comment]
Hi Shelby
I find myself at a point where I don't know what to do next. What that means is, I think its done. I am sure there may be an I without a dot or a T without a cross, but my todo list is empty. I was initially planning to make the device a three port device by using the SPI interface but that wont work since the SPI interface is being used by the SD Card interface.
Any requests for what happens next?
Martin
    On Thursday, October 29, 2020, 06:06:22 PM EDT, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
  pull request for flashtool has been created. This uses esptool.py for non windows and a python shell program for windows execution. Not sure this will be the final configuration but it is working on my latest ESP32
Martin
    On Thursday, October 29, 2020, 09:34:05 AM EDT, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
  Hi Shelby
It would be great if we could go with python on the linux/unix platforms. I will grab the latest python version and see if I can get it to work and then convert it to an exe. I also have a bunch of minor fixes that I will submit today.
Martin

    On Thursday, October 29, 2020, 08:36:06 AM EDT, Shelby Merrick <notifications@github.com> wrote:  
 
 


I know there's py2exe for Window, and that may be the only platform we need to compile for. I'd say 99% of the Linux users would already have Python installed from their distro. I need to look at MacOS and see if it's there by default as well.

**Comment by forkineye** [comment]
> Hi Shelby I find myself at a point where I don't know what to do next. What that means is, I think its done. I am sure there may be an I without a dot or a T without a cross, but my todo list is empty. I was initially planning to make the device a three port device by using the SPI interface but that wont work since the SPI interface is being used by the SD Card interface. Any requests for what happens next?

First, I want to say thank you again for all the hard work you've put into this.  With Halloween over, I can really focus on this now. I'm going to change the Master branch to use the new flash tools today and get a 3.2 release out for Mac users who can't flash, then I'm going to dig in on Unify (4.0) and get Travis back up building binary releases.  We'll start getting lots of feedback once the Travis builds start posting.  I

**Comment by MartinMueller2003** [comment]
I had an issue with the flash tool for a factory fresh ESP32. Even though everything loaded properly, the SW crashed as soon as it tried to read the config files. It looks like there are a few additional files that we should be uploading. Below is a copy of the Arduino flash command. It actually uploads multiple files. I find it interesting that it uploads a partition file. I suspect that missing partition information could make the ESP32 crash. I made the mistake of uploading to the factory fresh device using the Arduino IDE and after that all uploads using the flash tool worked. I suspect the flash tool needs to upload those files as well.
C:\Users\mmueller\AppData\Local\Arduino15\packages\esp32\tools\esptool_py\2.6.1/esptool.exe --chip esp32 --port COM4 --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0xe000 C:\Users\mmueller\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4/tools/partitions/boot_app0.bin 0x1000 C:\Users\mmueller\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4/tools/sdk/bin/bootloader_dio_80m.bin 0x10000 C:\Users\mmueller\AppData\Local\Temp\arduino_build_126534/ESPixelStick.ino.bin 0x8000 C:\Users\mmueller\AppData\Local\Temp\arduino_build_126534/ESPixelStick.ino.partitions.bin 
Martin
    On Tuesday, November 3, 2020, 08:43:42 AM EST, Shelby Merrick <notifications@github.com> wrote:  
 
 



Hi Shelby I find myself at a point where I don't know what to do next. What that means is, I think its done. I am sure there may be an I without a dot or a T without a cross, but my todo list is empty. I was initially planning to make the device a three port device by using the SPI interface but that wont work since the SPI interface is being used by the SD Card interface. Any requests for what happens next?


First, I want to say thank you again for all the hard work you've put into this. With Halloween over, I can really focus on this now. I'm going to change the Master branch to use the new flash tools today and get a 3.2 release out for Mac users who can't flash, then I'm going to dig in on Unify (4.0) and get Travis back up building binary releases. We'll start getting lots of feedback once the Travis builds start posting. I

**Pull request merged**
