### PR TITLE
Add PWM supprt, user gamma, led brightness

### PR DESCRIPTION
**Pull request by penfold42**
PWM:
- Web config under device section
- Map any Dmx channel to a PWM gpio output
- Coexists with both serial and pixel mode
- Selectively enable each gpio pin with optional inverted logic and digital rather than analog mode
- Conditional compile flag if you don't want to include this.

gamma and brightness
- Web UI to configure gamma value and brightness
- SVG graph of the resulting curve

Note: i screwed up a merge to had to recreate the branch. This replaces #66

### CODE REVIEW

**Comment by forkineye** [comment]
Did you mean to add all the includes back into the ESPixelStick.h header?  Haven't had a chance to test it yet.

**Comment by penfold42** [comment]
I did it in https://github.com/penfold42/ESPixelStick/commit/2aea9d290b2cd6dc40a534921bce2e5d5f396e67

I didn’t delve into it but I think it was needed to build with https://github.com/plerup/makeEspArduino

**Comment by forkineye** [comment]
Finally merged.  Cleaned a few things up, but don't think I broke anything. Thanks!

**Comment by fbpinheiro** [comment]
Hello, I have a esp8266 with espixelstick, I can control the GPIOs (pwm) 5, 12 and 14 with vixen 3?

**Comment by penfold42** [comment]
Should be able to. You’ll need :
- an esp8266 which breaks outs this gpios;
- the e131 plugin for vixen 3
- to build espixelstick from source as the prebuilt binaries have it disabled

You can then use the webUI in espixelstick to map this gpios to DMX channels

**Pull request merged**
