### PR TITLE
Add support for multiple universes over multicast

### PR DESCRIPTION
**Pull request by asavartsov**
Kind of easy actually, just join to additional universe adrresses before listening using lower level API

### CODE REVIEW

**Comment by forkineye** [comment]
I'm just getting back to working on this project. I was having reliability issues with multicast last year, so didn't focus much time on it.  How many pixels are you testing this with, and experienced any issues?  I'm just getting up to speed on the ESP8266 SDK and Arduino updates since I've last worked on this.

**Comment by marcfon** [comment]
Would be nice to see this added in the main branch.

@forkineye great that you're back on the project. Been running 1.3 release for a few months now without any major issues.

**Comment by asavartsov** [comment]
I haven't experienced any issues yet. I'm testing with single ESP-12 @ 160MHz module and 60 leds strip now, waiting for more ESPs and leds to arrive. I have tested it with single universe per strip, with 4 universes per controller (looking to only first 60 obviously) and with 4 universes 15 leds, all multicast. As E1.31 source I've used Jinx!, QLC+, Madrix and Lightjams, all worked fine, no visible delays or skipping when signal strength is good. If I move ESP for enough walls between me and AP to signal to drop strip shines with last state until I go back and everything restores back to normal. It keeps wiresless connection better than my phone, to say. Actually, I'm very excited with stability and how nice this firmware runs out of the box. Waiting for another 5 ESPs to test all of them in a single network!

**Comment by forkineye** [comment]
I'm keeping the E131 library seperate now and implemented it here - https://github.com/forkineye/E131/commit/be445e9183566e99626f2cb0fe35786bdca47e2c.  Supported in ESPixelStick with https://github.com/forkineye/ESPixelStick/commit/877fb9003e07ccbdda4dfe72c356cbc9e50e4e30.  Thanks!

**Pull request closed without merging**
