### PR TITLE
Harmonize on common code

### PR DESCRIPTION
**Pull request by LabRat3K**
Code clean-up. By using a common name for the pixels vs serial drivers, we can remove several instances of #ifdef PIXEL. 
Fewer places to change if/when something other than PIXEL or SERIAL is introduced. (Like .. say.. a bridge to NRF24L01 wireless network). :)

### CODE REVIEW

**Comment by forkineye** [comment]
You may want to look at the Unify branch. We've unified all pixel and serial code along with adding a lot more.  Once that branch is stable, it'll be moved to main.

**Comment by MartinMueller2003** [comment]
Have you looked at the UNIFY branch? We have Pixels, GECE, Serial protocols, relays and servos all in one build with the only ifdefs controlling ESP8266 vs ESP32 library includes.

**Comment by LabRat3K** [comment]
Thx.  Will take a look.  Plan was to add another output type “NRF” driver so that I can create an E1.31 to NRF bridge for my legacy devices.  
Could be ifdef’d or could be a complete fork and stripped down version as I doubt there will be huge demand outside of a select few.  
Do you want me to cancel the pull request?
AW


Sent from Yahoo Mail for iPhone


On Wednesday, February 10, 2021, 3:54 PM, Shelby Merrick <notifications@github.com> wrote:




You may want to look at the Unify branch. We've unified all pixel and serial code along with adding a lot more. Once that branch is stable, it'll be moved to main.

**Comment by forkineye** [comment]
The Unify branch has changed vastly.  I'd try adding it there as an output module.

**Comment by MartinMueller2003** [comment]
Leave the pull request. If it makes things better then it is a good thing.
I would be happy to help you add an NRF output driver on the unify branch. It is a very different architecture than V3.
Martin
    On Wednesday, February 10, 2021, 03:59:28 PM EST, LabRat <notifications@github.com> wrote:  
 
 

Thx.  Will take a look.  Plan was to add another output type “NRF” driver so that I can create an E1.31 to NRF bridge for my legacy devices.  
Could be ifdef’d or could be a complete fork and stripped down version as I doubt there will be huge demand outside of a select few.  
Do you want me to cancel the pull request?
AW


Sent from Yahoo Mail for iPhone


On Wednesday, February 10, 2021, 3:54 PM, Shelby Merrick <notifications@github.com> wrote:




You may want to look at the Unify branch. We've unified all pixel and serial code along with adding a lot more. Once that branch is stable, it'll be moved to main.

**Comment by LabRat3K** [comment]
Travis failure seems unrelated to the pull request. Is this typical?
`Hash mismatch for dist/x86_64-linux-gnu.mkspiffs-7fefeac.1563313032.tar.gz`

**Comment by MartinMueller2003** [comment]
I would try running the build again. That almost looks like there was an error in the download or that file is no longer available.

**Comment by LabRat3K** [comment]
> I would try running the build again. That almost looks like there was an error in the download or that file is no longer available.

Not sure how to do that. This wasn't a local build failure, it was the automated TRAVIS CI system. Is there a way to re-start the build? Or clone the build job to a new one?  [Sorry.. my first time encountering TRAVIS]

**Comment by MartinMueller2003** [comment]
I dont see a button for it. Maybe cancel the pull request and retry it?

**Pull request closed without merging**
