### PR TITLE
Updated copyright date to 2021

### PR DESCRIPTION
**Pull request by MartinMueller2003**
Also checkpointing playlist files.

### CODE REVIEW

**Review by forkineye — COMMENTED** [review]
Can you revert the .travis.yml changes for now? Will add ESP32 builds in github actions.

**Comment by MartinMueller2003** [comment]
Just tried to do this and lost four days of work. Does the term "Less than pleased" come to mind?
Martin
    On Wednesday, January 20, 2021, 09:21:34 AM EST, Shelby Merrick <notifications@github.com> wrote:  
 
 


@forkineye commented on this pull request.

Can you revert the .travis.yml changes for now? Will add ESP32 builds in github actions.

**Comment by forkineye** [comment]
> Just tried to do this and lost four days of work. Does the term "Less than pleased" come to mind?
Ouch, how did that happen?  I thought you'd just remove the items and re-commit the file.

**Comment by MartinMueller2003** [comment]
I tried to do a revert. It reverted all of my files instead of just the one file. My own fault. I should have checkpoitned the work.
    On Wednesday, January 20, 2021, 01:46:19 PM EST, Shelby Merrick <notifications@github.com> wrote:  
 
 



Just tried to do this and lost four days of work. Does the term "Less than pleased" come to mind?


Ouch, how did that happen? I thought you'd just remove the items and re-commit the file.

**Comment by MartinMueller2003** [comment]
Travis has been properly reverted. Also have updated the file play mechanism for both local and remote playing. Playlist is next.

**Comment by forkineye** [comment]
Looks like fseq.h didn't get checked in - https://travis-ci.org/github/forkineye/ESPixelStick/builds/755694013#L2284

**Comment by MartinMueller2003** [comment]
Grr. I split the definitions into s stand alone file so they can be shared between FPP Discovery and the new FSEQ file player class. Forgot to add it to GIT.
Martin
    On Friday, January 22, 2021, 12:06:06 PM EST, Shelby Merrick <notifications@github.com> wrote:  
 
 


Looks like fseq.h didn't get checked in - https://travis-ci.org/github/forkineye/ESPixelStick/builds/755694013#L2284

**Comment by forkineye** [comment]
@MartinMueller2003 What version of ArduinoJson are you on? It broke in Travis - https://travis-ci.org/github/forkineye/ESPixelStick/builds/755728644#L2330

**Comment by MartinMueller2003** [comment]
did not change it in months. not sure why it would break.
martin

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 22, 2021 at 15:54, Shelby Merrick<notifications@github.com> wrote:   


@MartinMueller2003 What version of ArduinoJson are you on? It broke in Travis - https://travis-ci.org/github/forkineye/ESPixelStick/builds/755728644#L2330

**Comment by MartinMueller2003** [comment]
This error was caused by the upload of a file that was in the process of being modified. That is a real bug in the code, not a change in ArduinoJson. I have disabled that code and uploaded a file that should compile. My travis just reported success. on the version waiting to be merged to your branch.
Martin
    On Friday, January 22, 2021, 06:59:01 PM EST, Martin Mueller <martinmueller2003@yahoo.com> wrote:  
 
 did not change it in months. not sure why it would break.
martin

Sent from Yahoo Mail on Android 
 
  On Fri, Jan 22, 2021 at 15:54, Shelby Merrick<notifications@github.com> wrote:   


@MartinMueller2003 What version of ArduinoJson are you on? It broke in Travis - https://travis-ci.org/github/forkineye/ESPixelStick/builds/755728644#L2330

**Pull request merged**
